- name: upload assets to s3 bucket
  community.aws.s3_sync:
    bucket: "{{ website_bucket }}"
    file_change_strategy: force
    file_root: "{{ playbook_dir }}/../dist/"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ aws_region }}"
    exclude: "*.html"


- name: upload html to s3 bucket
  community.aws.s3_sync:
    bucket: "{{ website_bucket }}"
    file_change_strategy: force
    file_root: "{{ playbook_dir }}/../dist/"
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ aws_region }}"
    cache_control: "public, max-age=0"
    include: "*.html"
